### PR TITLE
Duplicate HTTP headers on reqwest

### LINKED ISSUE #156: Headers duplicated on expired requests when using custom headers
I ran into a problem where I was seeing duplicate headers on requests which had expired in the cache.

When sending a request with `.header("x-test", "test")` set, the system would cache the response and return from cache before expiration. However, once the response expired, the new request would have duplicated headers, like so:
```
x-test: test
x-test: test
```

I was able to reproduce it somewhat in the test below. However, this failed with:

```
x-test: test,test
```
which is slightly different than what I was seeing, but also incorrect.
I can't tell if it's a different issue or not.

The test added to `http-cache-reqwest/src/test.rs`:
```rust
#[tokio::test]
async fn duplicate_header() -> Result<()> {
    let now = SystemTime::now();
    let expires = SystemTime::now() + Duration::from_secs(2);

    let mock_server = MockServer::start().await;
    let mock = Mock::given(method(GET)).and(header("x-test", "test"))
        .respond_with(
            ResponseTemplate::new(200)
                .insert_header("expires", httpdate::fmt_http_date(now))
                .set_body_bytes("ok"),
        )
        .expect(2);
    let mock_guard = mock_server.register_as_scoped(mock).await;
    let url = format!("{}/", &mock_server.uri());
    let manager = create_cache_manager();

    // Construct reqwest client with cache defaults
    let client = ClientBuilder::new(Client::new())
        .with(Cache(HttpCache {
            mode: CacheMode::Default,
            manager: manager.clone(),
            options: Default::default(),
        }))
        .build();

    let resp1 = client.get(url.clone()).header("x-test", "test").send().await?;

    let wait_until = expires + Duration::from_secs(2);
    while SystemTime::now() < wait_until {
        sleep(Duration::from_millis(100)).await;
    }

    let resp2 = client.get(url.clone()).header("x-test", "test").send().await?;

    drop(mock_guard);

    assert_eq!(resp1.text().await?, "ok");
    assert_eq!(resp2.text().await?, "ok");

    Ok(())
}
```

Output:
```
Verification failed for a scoped mock:
- Mock #0.
	Expected range of matching incoming requests: == 2
	Number of matched incoming requests: 1

Received requests:
- Request #1
	GET http://localhost/
x-test: test
accept: */*
host: 127.0.0.1:35349

- Request #2
	GET http://localhost/
x-test: test,test
accept: */*
host: 127.0.0.1:35349
```

If you change the two `x-test` headers in the two responses to `test1` and `test2`, respectively, you get:
```
Received requests:
- Request #1
	GET http://localhost/
x-test: test1
accept: */*
host: 127.0.0.1:37749

- Request #2
	GET http://localhost/
x-test: test2,test2
accept: */*
host: 127.0.0.1:37749
```

### PR DESCRIPTION
**Pull request by kennethjor**
Closes #156

### CODE REVIEW

File: http-cache-reqwest/src/test.rs [hunk 1]
```diff
@@ -704,6 +706,49 @@ async fn revalidation_200() -> Result<()> {
...
+            options: Default::default(),
+        }))
+        .build();
+
+    let resp1 = client.get(url.clone()).header("x-test", "test").send().await?;
+
+    let wait_until = expires + Duration::from_secs(2);
+    while SystemTime::now() < wait_until {
+        sleep(Duration::from_millis(100)).await;
+    }
```
Comment (kennethjor) [inline http-cache-reqwest/src/test.rs:740]: @06chaynes There's probably a better way of simulating an expired cache object

**Comment by 06chaynes** [comment]
Thanks! I will complete the remaining updates and modify those tests.
